### PR TITLE
add com.bnyro.translate

### PR DESCRIPTION
**Pull request by SuhasDissa**
### I think this app should be in this list.
GitHub Repo : https://github.com/Bnyro/TranslateYou
F-Droid : https://f-droid.org/packages/com.bnyro.translate/

### CODE REVIEW

**Review by MuntashirAkon — APPROVED** [review]

**Comment by shuvashish76** [comment]
Add `reason` to something like:
> Modern & customizable translator app that supports multiple engines.

Note: LingvaTranslate which [uses Google Translate®](https://github.com/Bnyro/TranslateYou#supported-translation-engines) to fetch translations. 
- https://github.com/Bnyro/TranslateYou/issues/10
- https://gitlab.com/fdroid/fdroiddata/-/merge_requests/12723

Nothing mentioned as such in F-Droid description/metadata. Add that info here if you think necessary, I'll ask them to add it to description anyway.

**Comment by MuntashirAkon** [comment]
> Add `reason` to something like:
> 
> > Modern & customizable translator app that supports multiple engines.

Reason should not be used as a promotion banner. If an app is added without specifying any `reason`, it means that the app offers almost equal or better features than the bloatware.

> LingvaTranslate which [uses Google Translate®](https://github.com/Bnyro/TranslateYou#supported-translation-engines) to fetch translations.

Yes, I've already reviewed the app. The default translation is **LibreTranslate** which makes **Lingva** an opt-out feature, therefore, we do not need to specify anything here. But in any case, no third-party server can ever comply with the FOSS principles unless there exists an open protocol to verify the server is actually using completely unmodified code. Only self-hosting can fix that, which I think most FOSS-lovers are already aware of.

**Comment by shuvashish76** [comment]
> Why this is suggested, under 100 words.

IMO "supports multiple engines" should be mentioned there as thats the main reason it's suggested over other proprietary/[foss translators](https://github.com/offa/android-foss#-translation). This is not an endorsement.

**Comment by MuntashirAkon** [comment]
> IMO "supports multiple engines" should be mentioned there as thats the main reason it's suggested over other proprietary/[foss translators](https://github.com/offa/android-foss#-translation). This is not an endorsement.

This is definitely one of the criteria due to which it was selected above others. But does an end-user know what “multiple engines” is supposed to mean? No. For future reference, here's why I accepted it as a good suggestions over other apps such as LibreTranslator, (Lentil) Translate, DeepL, etc.:

1. Supports multiple translation engines
2. Supports more languages (as a byproduct of 1)
3. Supports translation of images via in-house OCR tool
4. Has a good and interactive UI with useful information at the bottom (such as detected language and pronunciation)
5. Supports translating via context menus
6. Has a copyleft license (a subclass of OSI licenses that are more preferable over others)
7. Supports translation history
8. Supports invoking translation manually
9. Provides the ability to fetch translations from multiple sources at once
10. Can auto-detect language

Many of these features aren't available even in the proprietary software.

The issues were these:
11. The settings page has design and usability issues, especially in small screens
12. The app also has accessibility issues (not surprising since it's developed using JetPack Compose)
13. No support for Android TV
14. `android.permission.RECORD_AUDIO` is present which does not seem to have any associated features
15. Network security issues: Permits HTTP (clear texts), trusts user certificates, allows input of arbitrary website with protocol without much verification

**Comment by Bnyro** [comment]
Someone told me about this issue, just to give some reasoning:
* `android.permission.RECORD_AUDIO` allows users with Google services installed to insert text by voice using Google's STT engine
* clear network traffic is definitely an issue, however it's the only way users can use self-hosted, local instance of LibreTranslate or similar FOSS services
* who uses translators on a TV? but that's only my opinion
* accessibility issues are addressed when an issue is opened with a detailed explanation what the problem is

**Pull request merged**
